services:
    ns_local:
        build:
            context: ..
        image: oqs-bind
        tty: true
        entrypoint:
            - /init.bash 
        command: ${ALG} ${FRAG_MODE} ${DEBUG}
        volumes:
            - ./init.bash:/init.bash
            - ./dsset-example.local.:/dsset-example.local.
            - ./named.conf:/named.conf
            - ./${DB}:/db.local
            - ./data:/tmp/
        ports:
            - "2053:53/tcp"
            - "2053:53/udp"
        networks:
            bind9_net:
                ipv4_address: 172.20.0.3

networks:
    bind9_net:
        external: true