services:
    ns_root:
        build:
            context: ..
        image: oqs-bind
        tty: true
        entrypoint:
            - /init.bash 
        command: ${ALG}
        volumes:
            - ./init.bash:/init.bash
            - ../docker scripts/run_bind.bash:/run_bind.bash
            - ../docker scripts/set_udp_fragmentation.bash:/set_udp_fragmentation.bash
            - ../docker scripts/update_bind.bash:/update_bind.bash
            - ./named.conf:/named.conf
            - ./${DB}:/db.root
            - ./data:/tmp/
            - ./dsset-local.:/dsset-local.
        ports:
            - "53:53/tcp"
            - "53:53/udp"
        networks:
            bind9_net:
                ipv4_address: 172.20.0.2

networks:
    bind9_net:
        external: true