services:
    ns_example_local:
        build:
            context: ..
        image: oqs-bind
        tty: true
        entrypoint:
            - /init.bash 
        command: ${ALG} ${FRAG_MODE} ${DEBUG}
        volumes:
            - ./init.bash:/init.bash
            - ./named.conf:/named.conf
            - ./${DB}:/db.example.local
            - ./data:/tmp/
        ports:
            - "1053:53/tcp"
            - "1053:53/udp"
        networks:
            bind9_net:
                ipv4_address: 172.20.0.4
        cap_add:
           - CAP_NET_BIND_SERVICE

networks:
    bind9_net:
        external: true