services:
    ns_example_local:
        build:
            context: ..
        image: oqs-bind
        tty: true
        entrypoint:
            - /init.bash 
        command: ${ALG}
        volumes:
            - ./init.bash:/init.bash
            - ./named.conf:/named.conf
            - ./${DB}:/db.example.local
            - ./data:/tmp/
        ports:
            - "53:53/tcp"
            - "53:53/udp"
        networks:
            bind9_net:
                ipv4_address: 172.20.0.4

networks:
    bind9_net:
        external: true